<?php

GRADE_TREE
    ->top_element[
        'object' => GRADE_CATEGORY (36),
        'type' => 'category',
        'depth' => '1',
        'children' => [
            2 => [
                'object' => GRADE_ITEM (101),
                'type' => 'item',
                'depth' => '1',
                'eid' => 'ig101',
                'prev' => 0,
                'next' => 3,
            ],
            3 => [
                'object' => GRADE_ITEM (102),
                'type' => 'item',
                'depth' => '1',
                'eid' => 'ig102',
                'prev' => 2,
                'next' => 7,
            ],
            7 => [
                'object' => GRADE_CATEGORY (37),
                'type' => 'category',
                'depth' => '2',
                'children' => [
                    4 => [
                        'object' => GRADE_ITEM (104),
                        'type' => 'item',
                        'depth' => '2',
                        'eid' => 'ig104',
                        'prev' => 0,
                        'next' => 5,
                    ],
                    5 => [
                        'object' => GRADE_ITEM (105),
                        'type' => 'item',
                        'depth' => '2',
                        'eid' => 'ig105',
                        'prev' => 4,
                        'next' => 6,
                    ],
                    6 => [
                        'object' => GRADE_ITEM (106),
                        'type' => 'item',
                        'depth' => '2',
                        'eid' => 'ig106',
                        'prev' => 5,
                        'next' => 3,
                    ],
                    3 => [
                        'object' => GRADE_ITEM (103),
                        'type' => 'categoryitem',
                        'depth' => '2',
                        'eid' => 'ig103',
                        'prev' => 6,
                        'next' => 0,
                    ]
                ],
                'eid' => 'cg37',
                'prev' => 3,
                'next' => 8,
                'rowspan' => 5,
            ],
            8 => [
                'object' => GRADE_ITEM (107),
                'type' => 'item',
                'depth' => '1',
                'eid' => 'ig107',
                'prev' => 7,
                'next' => 17,
            ],
            17 => [
                'object' => GRADE_CATEGORY (38),
                'type' => 'category',
                'depth' => '2',
                'children' => [
                    9 => [
                        'object' => GRADE_ITEM (109),
                        'type' => 'item',
                        'depth' => '2',
                        'eid' => 'ig109',
                        'prev' => 0,
                        'next' => 15,
                    ],
                    15 => [
                        'object' => GRADE_CATEGORY (40),
                        'type' => 'category',
                        'depth' => '3',
                        'children' => [
                            10 => [
                                'object' => GRADE_ITEM (112),
                                'type' => 'item',
                                'depth' => '3',
                                'eid' => 'ig112',
                                'prev' => 0,
                                'next' => 11,
                            ],
                            11 => [
                                'object' => GRADE_ITEM (113),
                                'type' => 'item',
                                'depth' => '3',
                                'eid' => 'ig113',
                                'prev' => 10,
                                'next' => 14,
                            ],
                            14 => [
                                'object' => GRADE_CATEGORY (41),
                                'type' => 'category',
                                'depth' => '4',
                                'children' => [
                                    12 => [
                                        'object' => GRADE_ITEM (116),
                                        'type' => 'item',
                                        'depth' => '4',
                                        'eid' => 'ig116',
                                        'prev' => 0,
                                        'next' => 13,
                                    ],
                                    13 => [
                                        'object' => GRADE_ITEM (117),
                                        'type' => 'item',
                                        'depth' => '4',
                                        'eid' => 'ig117',
                                        'prev' => 12,
                                        'next' => 11,
                                    ],
                                    11 => [
                                        'object' => GRADE_ITEM (115),
                                        'type' => 'categoryitem',
                                        'depth' => '4',
                                        'eid' => 'ig115',
                                        'prev' => 13,
                                        'next' => 0,
                                    ],
                                ],
                                'eid' => 'cg41',
                                'prev' => 11,
                                'next' => 9,
                                'rowspan' => 4,
                            ],
                            9 => [
                                'object' => GRADE_ITEM (111),
                                'type' => 'categoryitem',
                                'depth' => '3',
                                'eid' => 'ig111',
                                'prev' => 14,
                                'next' => 0,
                            ],
                        ],
                        'eid' => 'cg40',
                        'prev' => 9,
                        'next' => 16,
                        'rowspan' => 8,
                    ],
                    16 => [
                        'object' => GRADE_ITEM (114),
                        'type' => 'item',
                        'depth' => '2',
                        'eid' => 'ig114',
                        'prev' => 15,
                        'next' => 8,
                    ],
                    8 => [
                        'object' => GRADE_ITEM (108),
                        'type' => 'categoryitem',
                        'depth' => '2',
                        'eid' => 'ig108',
                        'prev' => 16,
                        'next' => 0,
                    ],
                ],
                'eid' => 'cg38',
                'prev' => 8,
                'next' => 1,
                'rowspan' => 12,
            ],
            1 => [
                'object' => GRADE_ITEM (100),
                'type' => 'courseitem',
                'depth' => '1',
                'eid' => 'ig100',
                'prev' => 17,
                'next' => 0,
            ],
        ],
        'eid' => 'cg36',
        'rowspan' => 22,
    ]
    ->levels[
        0 => [
            0 => [
                'object' => GRADE_CATEGORY,
                'type' => 'category',
                'depth' => 1,
                'children' => [
                    2 => [
                        'object' => GRADE_ITEM,
                        'type' => 'item',
                        'depth' => '1',
                        'eid' => 'ig101',
                        'prev' => 0,
                        'next' => 3,
                    ],
                    3 => [
                        'object' => GRADE_ITEM,
                        'type' => 'item',
                        'depth' => '1',
                        'eid' => 'ig102',
                        'prev' => 2,
                        'next' => 7,
                    ],
                    7 => [
                        // 4036
                    ],
                ],
            ],
        ],
    ],